# Generated by Django 4.1.3 on 2023-06-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
    ]
