# Generated by Django 4.1.3 on 2023-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_firebase_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
